apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: sre-demo
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: 'order-api'
        static_configs:
          - targets: ['order-api-service:80']