apiVersion: v1
kind: Service
metadata:
  name: order-api-service
  namespace: sre-demo
spec:
  type: ClusterIP
  selector:
    app: order-api
  ports:
    - name: http
      port: 80
      targetPort: 8000